<?php
/**
 * ECCM – Database Configuration
 * 
 * This file is auto-generated by admin settings.
 * You can also edit it manually.
 */

// Default config – overwritten by config.local.php if it exists
$db_config = [
    'host'     => 'localhost',
    'port'     => 3306,
    'dbname'   => 'eccm_db',
    'username' => 'root',
    'password' => '',
    'charset'  => 'utf8mb4',
];

// Mail settings for password reset
$mail_config = [
    'from_email' => 'noreply@example.com',
    'from_name'  => 'ECCM System',
    'smtp_host'  => '',        // leave empty for PHP mail()
    'smtp_port'  => 587,
    'smtp_user'  => '',
    'smtp_pass'  => '',
    'base_url'   => '',        // auto-detect if empty
];

// App settings
$app_config = [
    'session_lifetime' => 3600,     // 1 hour
    'token_lifetime'   => 3600,     // password reset token: 1 hour
];

// Override with local config if exists
$local_config = __DIR__ . '/config.local.php';
if (file_exists($local_config)) {
    include $local_config;
}
